meta_product_name: "City Makeover"
meta_title: "City Makeover - Improving our communities together"
meta_description: "Find an issue, snap and upload a photo, submit and let others vote and the city repairs!"
meta_image: "cover.png"
